include:
  - ./server/docker-compose.yml
  - ./client/docker-compose.yml

networks:
  server:
    driver: bridge

services:
  traefik:
    image: traefik:v3.1
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  web-server:
    image: nginx:alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./server:/workdir
      - server-storage:/workdir/storage
    depends_on:
      server-app: { condition: service_started }
    labels:
      - traefik.enable=true
      - traefik.http.routers.web-server.rule=Host(`${BASE_DOMAIN?}`)
          && (PathPrefix(`/api`) 
          || PathPrefix(`/cp`) 
          || PathPrefix(`/livewire`) 
          || PathPrefix(`/storage`))
      - traefik.docker.network=server