version: '3.9'

services:
    server-app:
        build:
            context: ..
            dockerfile: laravel.Dockerfile
        restart: unless-stopped
        env_file: .env.common
        volumes:
            - ./:/workdir
        depends_on:
            server-postgres: { condition: service_healthy }
        ports:
            - '9000:9000'
        networks:
            - server

    server-nginx:
        image: nginx:latest
        ports:
            - '80:80'
        volumes:
            - ./.nginx/nginx.conf/default.conf:/etc/nginx/conf.d/default.conf
            - ./:/workdir
        restart: unless-stopped
        depends_on:
            server-app: { condition: service_started }
        networks:
            - server

    server-postgres:
        image: postgres:15-alpine
        environment:
            - POSTGRES_DB=${POSTGRES_DB?}
            - POSTGRES_USER=${POSTGRES_USER?}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD?}
        ports:
            - '5433:5432'
        restart: always
        healthcheck:
            test: pg_isready -d ${POSTGRES_DB?} -U ${POSTGRES_USER?}
        volumes:
            - server-postgres:/var/lib/postgresql/data
        networks:
            - server

volumes:
    server-postgres: { }

networks:
    server:
        driver: bridge
